-- ===================================
-- mission:sync後に実行するシードデータ
-- ミッションのslugで参照するため、mission:sync後に実行が必要
-- ===================================
--
-- 旧: ポスティングミッション（posting-activity-magazine / posting-flyer）の
-- achievements / mission_artifacts / posting_activities シード。
-- 浜通りクエストの運用計画（1000pt 3ステップ）に無いミッションのため、
-- missions テーブルからは削除済み。参照先ミッションが存在しないと
-- mission_artifacts の外部キー制約に違反するため、このファイルからも撤去。
